import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';

export interface ReportMetadata {
  title: string;
  period: string;
  generatedAt: string;
  generatedBy: string;
  outletName: string;
}

export interface ReportSummaryItem {
  label: string;
  value: string | number;
}

export interface ReportSheetConfig {
  name: string;
  data: any[];
  columns: { header: string; key: string; width?: number; style?: Partial<ExcelJS.Style> }[];
}

export class ExcelExportService {
  private workbook: ExcelJS.Workbook;

  constructor() {
    this.workbook = new ExcelJS.Workbook();
    this.workbook.creator = 'Fere POS';
    this.workbook.lastModifiedBy = 'Fere POS';
    this.workbook.created = new Date();
    this.workbook.modified = new Date();
  }

  addMetadataSheet(metadata: ReportMetadata) {
    const sheet = this.workbook.addWorksheet('Metadata');
    
    sheet.columns = [
      { header: 'Property', key: 'property', width: 25 },
      { header: 'Value', key: 'value', width: 50 },
    ];

    const data = [
      { property: 'Report Title', value: metadata.title },
      { property: 'Period', value: metadata.period },
      { property: 'Generated At', value: metadata.generatedAt },
      { property: 'Generated By', value: metadata.generatedBy },
      { property: 'Outlet', value: metadata.outletName },
    ];

    sheet.addRows(data);

    // Style the header row
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4F46E5' } // Indigo-600 logic
    };
    headerRow.alignment = { vertical: 'middle', horizontal: 'center' };

    // Style data rows
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        row.getCell(1).font = { bold: true };
        row.getCell(1).alignment = { vertical: 'middle', horizontal: 'left' };
        row.getCell(2).alignment = { vertical: 'middle', horizontal: 'left', wrapText: true };
      }
    });

    return this;
  }

  addSummarySheet(summaryItems: ReportSummaryItem[]) {
    const sheet = this.workbook.addWorksheet('Summary');
    
    sheet.columns = [
      { header: 'Metric', key: 'label', width: 30 },
      { header: 'Value', key: 'value', width: 30 },
    ];

    sheet.addRows(summaryItems);

    // Style header
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4F46E5' }
    };

    // Style cells
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1) {
        row.getCell(1).font = { bold: true };
        row.getCell(2).alignment = { horizontal: 'right' };
      }
    });

    return this;
  }

  addDataSheet(config: ReportSheetConfig) {
    const sheet = this.workbook.addWorksheet(config.name);
    
    // Set columns
    sheet.columns = config.columns.map(col => ({
      header: col.header,
      key: col.key,
      width: col.width || 20,
      style: col.style
    }));

    // Add data
    sheet.addRows(config.data);

    // Style header
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4F46E5' }
    };
    headerRow.alignment = { vertical: 'middle', horizontal: 'center' };

    // Add borders to all cells
    sheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });

    return this;
  }

  async download(fileName: string) {
    const buffer = await this.workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    saveAs(blob, fileName.endsWith('.xlsx') ? fileName : `${fileName}.xlsx`);
  }
}
