import {
  StoreInfo,
  OperatingHours,
  TaxSettings,
  ReceiptSettings,
  PaymentMethodConfig,
} from "./types";

export const mockStoreInfo: StoreInfo = {
  id: "STORE-001",
  name: "Fere Coffee",
  slug: "fere-coffee",
  description:
    "Kafe modern dengan suasana nyaman dan menu kopi spesial dari biji pilihan nusantara. Menyediakan berbagai minuman, makanan ringan, dan pastry.",
  address: "Jl. Sudirman No. 123, Blok A Lt. 2",
  city: "Jakarta Selatan",
  province: "DKI Jakarta",
  postal_code: "12190",
  phone: "+62 21-5555-1234",
  email: "info@ferecafe.com",
  website: "https://ferecafe.com",
  logo: undefined,
  cover_image: undefined,
  tax_id: "01.234.567.8-901.000",
  business_type: "cafe",
  currency: "IDR",
  timezone: "Asia/Jakarta",
  is_active: true,
  created_at: "2024-01-15T08:00:00Z",
  updated_at: "2025-01-10T14:30:00Z",
};

export const mockOperatingHours: OperatingHours[] = [
  { day: "monday", is_open: true, open_time: "07:00", close_time: "22:00" },
  { day: "tuesday", is_open: true, open_time: "07:00", close_time: "22:00" },
  { day: "wednesday", is_open: true, open_time: "07:00", close_time: "22:00" },
  { day: "thursday", is_open: true, open_time: "07:00", close_time: "22:00" },
  { day: "friday", is_open: true, open_time: "07:00", close_time: "23:00" },
  { day: "saturday", is_open: true, open_time: "08:00", close_time: "23:00" },
  { day: "sunday", is_open: true, open_time: "08:00", close_time: "21:00" },
];

export const mockTaxSettings: TaxSettings = {
  is_tax_enabled: true,
  tax_name: "PPN",
  tax_rate: 11,
  is_tax_inclusive: true,
  tax_id_number: "01.234.567.8-901.000",
  is_service_charge_enabled: true,
  service_charge_rate: 5,
};

export const mockReceiptSettings: ReceiptSettings = {
  show_logo: true,
  show_store_name: true,
  show_address: true,
  show_phone: true,
  show_tax_id: false,
  header_text: "Terima kasih atas kunjungan Anda!",
  footer_text: "Barang yang sudah dibeli tidak dapat dikembalikan. Simpan struk ini sebagai bukti pembayaran.",
  show_cashier_name: true,
  show_customer_name: true,
  paper_size: "80mm",
  auto_print: true,
};

export const mockPaymentMethods: PaymentMethodConfig[] = [
  {
    id: "PAY-001",
    name: "Tunai",
    type: "cash",
    is_enabled: true,
    icon: "Banknote",
  },
  {
    id: "PAY-002",
    name: "BCA Transfer",
    type: "bank_transfer",
    is_enabled: true,
    icon: "Building2",
    account_name: "PT Fere Coffee Indonesia",
    account_number: "1234567890",
    fee_percentage: 0,
    fee_fixed: 0,
  },
  {
    id: "PAY-003",
    name: "BRI Transfer",
    type: "bank_transfer",
    is_enabled: true,
    icon: "Building2",
    account_name: "PT Fere Coffee Indonesia",
    account_number: "0987654321",
    fee_percentage: 0,
    fee_fixed: 0,
  },
  {
    id: "PAY-004",
    name: "GoPay",
    type: "e_wallet",
    is_enabled: true,
    icon: "Smartphone",
    fee_percentage: 1.5,
    fee_fixed: 0,
  },
  {
    id: "PAY-005",
    name: "OVO",
    type: "e_wallet",
    is_enabled: true,
    icon: "Smartphone",
    fee_percentage: 1.5,
    fee_fixed: 0,
  },
  {
    id: "PAY-006",
    name: "DANA",
    type: "e_wallet",
    is_enabled: false,
    icon: "Smartphone",
    fee_percentage: 1.5,
    fee_fixed: 0,
  },
  {
    id: "PAY-007",
    name: "QRIS",
    type: "qris",
    is_enabled: true,
    icon: "QrCode",
    fee_percentage: 0.7,
    fee_fixed: 0,
  },
  {
    id: "PAY-008",
    name: "Kartu Kredit / Debit",
    type: "credit_card",
    is_enabled: false,
    icon: "CreditCard",
    fee_percentage: 2.5,
    fee_fixed: 0,
  },
];
